-- USE QLNH;
set dateformat dmy;

-- DBCC CHECKIDENT ('FINANCIAL_HISTORY', RESEED, 0); -- DUNG DE RESET INT IDENTITY

INSERT INTO EMPLOYEE
VALUES ('NV001', N'Nguyễn Văn A', N'Đường X, Thủ Đức, Hồ Chí Minh', '0913579246', '091512345678', N'Đầu bếp', 10000000, 0);
INSERT INTO EMPLOYEE
VALUES ('NV002', N'Nguyễn Thị B', N'Đường Y, Quận Z, Hồ Chí Minh', '0932132132', '091367889072', N'Tạp vụ', 5000000, 0);
INSERT INTO EMPLOYEE
VALUES ('NV003', N'Trần Văn C', N'Đường N, Phường M, Tỉnh Kiên Giang', '0917426192', '047658123547', N'Nhân viên', 7000000, 0);
INSERT INTO EMPLOYEE
VALUES ('NV004', N'Lê Nguyễn D', N'Đường K, Phường L, Tỉnh Khánh Hoà', '0941253698', '091214657892', N'Đầu bếp', 10000000, 0);
INSERT INTO EMPLOYEE
VALUES ('NV005', N'Trần Huỳnh E', N'Đường U, Quận V, Hồ Chí Minh', '0947852645', '091512489657', N'Nhân Viên', 7000000, 0);

INSERT INTO CUSTOMER
VALUES ('KH001', N'Không Huỳnh Ngọc Hân', N'D6-Lô 14 Nguyễn Văn Tố, Phường Vĩnh Lạc, TP. Rạch Giá, Tỉnh Kiên Giang', '0915220130', '091305011238', 'hankhongg@gmail.com', 0);
INSERT INTO CUSTOMER
VALUES ('KH002', N'Ngô Quang Tiến', N'Đường X, Phường Y, TP. Rạch Giá, Tỉnh Kiên Giang', '0912548565', '091324578469', 'quangtienngo@gmail.com', 0);
INSERT INTO CUSTOMER
VALUES ('KH003', N'Phạm Thị Kiều Diễm', N'Đường N, Phường M, Tỉnh Khánh Hoà', '0327498240', '091458746325', 'diemphamdiem@gmail.com', 0);
INSERT INTO CUSTOMER
VALUES ('KH004', N'Huỳnh Kim Ngọc', N'D6-Lô 14 Nguyễn Văn Tố, Phường Vĩnh Lạc, TP. Rạch Giá, Tỉnh Kiên Giang', '0947333636', '091413647589', 'ngochuynh@gmail.com', 0);
INSERT INTO CUSTOMER
VALUES ('KH005', N'Đỗ Hoàng Anh Thư', N'Đường U, Quận V, Hồ Chí Minh', '0945214564', '091958463425', 'thudoo@gmail.com', 0);



INSERT INTO DINING_TABLE
VALUES (1, 1, 0);
INSERT INTO DINING_TABLE
VALUES (2, 1, 0);
INSERT INTO DINING_TABLE
VALUES (3, 1, 0);
INSERT INTO DINING_TABLE
VALUES (4, 1, 0);
INSERT INTO DINING_TABLE
VALUES (5, 1, 0);

INSERT INTO INGREDIENTS
VALUES ('NL001', 'Muối', '5', '0');
INSERT INTO INGREDIENTS
VALUES ('NL002', 'Đường mía', '5', '0');
INSERT INTO INGREDIENTS
VALUES ('NL003', 'Tiêu đen xay', '2', '0');
INSERT INTO INGREDIENTS
VALUES ('NL004', 'Bột ngọt', '2', '0');
INSERT INTO INGREDIENTS
VALUES ('NL005', 'Dầu ăn', '5', '0');

INSERT INTO INGREDIENTS
VALUES ('NL006', 'Tôm sú', '10.5', '0');
INSERT INTO INGREDIENTS
VALUES ('NL007', 'Bột chiên giòn', '2', '0');
INSERT INTO INGREDIENTS
VALUES ('NL008', 'Soda', '2', '0');
INSERT INTO INGREDIENTS
VALUES ('NL009', 'Trứng gà', '50', '0');

INSERT INTO MENU_ITEMS
VALUES ('MN01', 'FOOD', N'Tôm chiên bột', 'https://cdn.tgdd.vn/2021/07/CookRecipe/Avatar/tom-chien-xu-thumbnail.jpg', 0, 249000, 1, 0);
INSERT INTO MENU_ITEMS
VALUES ('MN02','FOOD', N'Cánh gà chiên nước mắm', 'https://media.cooky.vn/recipe/g3/25753/s800x500/recipe-cover-r25753.jpg', 0, 99000, 1, 0);
INSERT INTO MENU_ITEMS
VALUES ('MN03','FOOD', N'Cơm chiên hải sản', 'https://daubepgiadinh.vn/wp-content/uploads/2019/01/com-chien-hai-san-trung-muoi.jpg', 0, 119000, 1, 0);
INSERT INTO MENU_ITEMS
VALUES ('MN04', 'DRINK', N'Coca Cola', 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/5307ef37224391.57397a56d79da.jpg', 0, 15000, 1, 0);
INSERT INTO MENU_ITEMS
VALUES ('MN05', 'OTHER', N'Hạt sen hấp', 'https://th.bing.com/th/id/OIP.UG3dtOIrEndKpKjjs5dyWwHaHa?rs=1&pid=ImgDetMain', 0, 30000, 1, 0);
INSERT INTO MENU_ITEMS
VALUES ('MN06', 'FOOD', N'Ốc hương sốt me', 'https://th.bing.com/th/id/OIP.88npI5GCFQq7mvXtwnmAAAHaFw?rs=1&pid=ImgDetMain', 0, 99000, 1, 0);
INSERT INTO MENU_ITEMS
VALUES ('MN07', 'DRINK', N'Mirinda Xá Xị', 'https://th.bing.com/th/id/OIP.YATY9JLhUznhlWqtYsXzOwHaFj?rs=1&pid=ImgDetMain', 0, 15000, 1, 0);
INSERT INTO MENU_ITEMS
VALUES ('MN08', 'FOOD', N'Khoai tây chiên', 'https://th.bing.com/th/id/OIP.9MRg0jJkJqjT00lSwq3xdgAAAA?rs=1&pid=ImgDetMain', 0, 59000, 1, 0);


INSERT INTO RECIPES
VALUES ('1', '1', '0.01');
INSERT INTO RECIPES
VALUES ('1', '2', '0.02');
INSERT INTO RECIPES
VALUES ('1', '3', '0.005');
INSERT INTO RECIPES
VALUES ('1', '4', '0.002');
INSERT INTO RECIPES
VALUES ('1', '5', '0.05');
INSERT INTO RECIPES
VALUES ('1', '6', '0.3');
INSERT INTO RECIPES 
VALUES ('1', '7', '0.3');
INSERT INTO RECIPES
VALUES ('1', '8', '1');
INSERT INTO RECIPES
VALUES ('1', '9', '1');


INSERT INTO BOOKING
VALUES ('BK001', 2, 1, 2, '16-10-2024', '17-10-2024', 0, 0);
INSERT INTO BOOKING
VALUES ('BK002', 1, 2, 1, '20-10-2024', '21-10-2024', 1, 0);
INSERT INTO BOOKING
VALUES ('BK003', 3, 3, 3, '12-10-2024', '13-10-2024', 2, 1);


INSERT INTO RECEIPT
VALUES ('HD000001', 4, 3, 3, '14-10-2024', 0, 0); 
INSERT INTO RECEIPT
VALUES ('HD000002', 5, 4, 4, '15-10-2024', 0, 0); 


INSERT INTO RECEIPT_DETAILS
VALUES (1, 1, 2, 0);
INSERT INTO RECEIPT_DETAILS
VALUES (1, 3, 1, 0);
INSERT INTO RECEIPT_DETAILS
VALUES (1, 5, 1, 0);
INSERT INTO RECEIPT_DETAILS
VALUES (1, 7, 1, 0);

INSERT INTO RECEIPT_DETAILS
VALUES (2, 2, 1, 0);
INSERT INTO RECEIPT_DETAILS
VALUES (2, 3, 2, 0);
INSERT INTO RECEIPT_DETAILS
VALUES (2, 5, 1, 0);
INSERT INTO RECEIPT_DETAILS
VALUES (2, 7, 1, 0);

INSERT INTO STOCKIN
VALUES ('ST000001', '14-10-2024', 0);
INSERT INTO STOCKIN
VALUES ('ST000002', '13-10-2024', 0);

INSERT INTO STOCKIN_DETAILS_INGRE
VALUES (1, 1, 5, 6300);
INSERT INTO STOCKIN_DETAILS_INGRE
VALUES (1, 2, 5, 41000);
INSERT INTO STOCKIN_DETAILS_INGRE
VALUES (1, 3, 5, 200000);
INSERT INTO STOCKIN_DETAILS_INGRE
VALUES (1, 4, 5, 82500);
INSERT INTO STOCKIN_DETAILS_DRINK_OTHER
VALUES (1, 4, 72, 7000);
INSERT INTO STOCKIN_DETAILS_DRINK_OTHER
VALUES (1, 5, 30, 20000);
INSERT INTO STOCKIN_DETAILS_DRINK_OTHER
VALUES (1, 7, 72, 6000);

INSERT INTO STOCKIN_DETAILS_DRINK_OTHER
VALUES (2, 7, 36, 6000);
INSERT INTO STOCKIN_DETAILS_INGRE
VALUES (2, 6, 5.5, 500000);
INSERT INTO STOCKIN_DETAILS_INGRE
VALUES (2, 7, 3, 30000);
INSERT INTO STOCKIN_DETAILS_INGRE
VALUES (2, 8, 20, 24000);
INSERT INTO STOCKIN_DETAILS_INGRE
VALUES (2, 9, 20, 5000);
INSERT INTO STOCKIN_DETAILS_DRINK_OTHER
VALUES (2, 4, 36, 7000);

INSERT INTO ACCOUNT_ROLE VALUES (N'Admin');
INSERT INTO ACCOUNT_ROLE VALUES (N'NhanVien1');

--string to base64 to md5
INSERT INTO ACCOUNT
VALUES (N'admin', N'00aa5c2b106cdf9716590ac7e12be472', 'hankhongg@gmail.com', N'Không Huỳnh Ngọc Hân', N'Nữ', '10-06-2005', N'Đường Sư Minh Không, Phường Vĩnh Bảo, TP. Rạch Giá, Tỉnh Kiên Giang', '0915220130', 1, 0);
INSERT INTO ACCOUNT
VALUES (N'vanannguyen', N'eb4f9e0c9fcd25c4496c02ba54925161', 'vietgambo@gmail.com', N'Nguyễn Văn An', N'Nam', '28-11-2007', N'TP. Rạch Giá, Tỉnh Kiên Giang', '0941425621', 2, 0);

--edit test
UPDATE ACCOUNT
SET ACC_DISPLAYNAME = 'Admin'
WHERE ACC_USERNAME = 'admin'
--

--DELETE FROM ACCOUNT

-- bỏ giá trong menu items vào receipt details
UPDATE RECEIPT_DETAILS
SET PRICE = (SELECT 
ITEM_SPRICE FROM MENU_ITEMS WHERE MENU_ITEMS.ITEM_ID = RECEIPT_DETAILS.ITEM_ID);
-- tính tổng tiền trong receipt từ các receipt details
UPDATE RECEIPT
SET REC_PAY = ( SELECT SUM(PRICE * QUANTITY)
FROM RECEIPT_DETAILS WHERE RECEIPT.REC_ID = RECEIPT_DETAILS.REC_ID);
/* lấy giá từ stock in details ingre để tính tiền vốn cho một recipe = menu_item cprice nếu item_type = 'FOOD', nếu item_type = 'DRINK' hoặc item_type = 'OTHER'
thì lấy giá từ stock in drink other*/
UPDATE MENU_ITEMS
SET ITEM_CPRICE = ISNULL((
    SELECT SUM(R.INGRE_QUANTITY_KG * S.CPRICE)
    FROM RECIPES R
    JOIN STOCKIN_DETAILS_INGRE S 
    ON R.INGRE_ID = S.INGRE_ID
    WHERE R.ITEM_ID = MENU_ITEMS.ITEM_ID
    GROUP BY R.ITEM_ID
), 0)
WHERE ITEM_TYPE = 'FOOD';

UPDATE MENU_ITEMS
SET ITEM_CPRICE = (
    SELECT TOP 1 S.CPRICE
    FROM STOCKIN_DETAILS_DRINK_OTHER S
    WHERE S.ITEM_ID = MENU_ITEMS.ITEM_ID
)
WHERE ITEM_TYPE IN ('DRINK', 'OTHER');
/* SELECT ITEM_ID, ITEM_NAME, ITEM_TYPE, ITEM_CPRICE, ITEM_SPRICE
FROM MENU_ITEMS
ORDER BY ITEM_ID; */

-- tính tiền cho mỗi lần stock in dựa vào các stock in details
UPDATE STOCKIN -- tính từ bảng stock in details ingre
SET STO_PRICE = (
    SELECT SUM(SI.CPRICE * SI.QUANTITY_KG)
    FROM STOCKIN_DETAILS_INGRE SI
    WHERE SI.STO_ID = STOCKIN.STO_ID
)
WHERE STO_ID IN (SELECT STO_ID FROM STOCKIN_DETAILS_INGRE);

UPDATE STOCKIN -- cộng dồn tiếp từ bảng stock in details drink other
SET STO_PRICE = COALESCE(STO_PRICE, 0) + (
    SELECT SUM(SD.CPRICE * SD.QUANTITY_UNITS)
    FROM STOCKIN_DETAILS_DRINK_OTHER SD
    WHERE SD.STO_ID = STOCKIN.STO_ID
)
WHERE STO_ID IN (SELECT STO_ID FROM STOCKIN_DETAILS_DRINK_OTHER);

-- nhập thông tin thu, chi
INSERT INTO FINANCIAL_HISTORY (FIN_DATE, DESCRIPTION, TYPE, AMOUNT, REFERENCE_ID, REFERENCE_TYPE)
SELECT REC_TIME, N'Doanh thu từ hóa đơn', 'INCOME', REC_PAY, REC_ID, 'RECEIPT'
FROM RECEIPT
WHERE REC_ID = 1;
INSERT INTO FINANCIAL_HISTORY (FIN_DATE, DESCRIPTION, TYPE, AMOUNT, REFERENCE_ID, REFERENCE_TYPE)
SELECT REC_TIME, N'Doanh thu từ hóa đơn', 'INCOME', REC_PAY, REC_ID, 'RECEIPT'
FROM RECEIPT
WHERE REC_ID = 2;

INSERT INTO FINANCIAL_HISTORY (FIN_DATE, DESCRIPTION, TYPE, AMOUNT, REFERENCE_ID, REFERENCE_TYPE)
SELECT STO_DATE, N'Chi phí nhập kho', 'EXPENSE', STO_PRICE, STO_ID, 'STOCKIN'
FROM STOCKIN;
-- -------------tính lợi nhuận
--SELECT 
--    FORMAT(FIN_DATE, 'yyyy-MM') AS Month,
--    SUM(CASE WHEN TYPE = 'INCOME' THEN AMOUNT ELSE 0 END) AS Total_Income,
--    SUM(CASE WHEN TYPE = 'EXPENSE' THEN AMOUNT ELSE 0 END) AS Total_Expense,
--    SUM(CASE WHEN TYPE = 'INCOME' THEN AMOUNT ELSE 0 END) - SUM(CASE WHEN TYPE = 'EXPENSE' THEN AMOUNT ELSE 0 END) AS Net_Profit
--FROM FINANCIAL_HISTORY
--GROUP BY FORMAT(FIN_DATE, 'yyyy-MM')
--ORDER BY Month;

SELECT * FROM MENU_ITEMS
SELECT * FROM RECEIPT_DETAILS
SELECT * FROM RECEIPT
SELECT * FROM STOCKIN_DETAILS_INGRE
SELECT * FROM STOCKIN_DETAILS_DRINK_OTHER
SELECT * FROM STOCKIN
SELECT * FROM FINANCIAL_HISTORY

